### ISSUE TITLE
Second and subsequent table pages clipping with header 

### ISSUE THREAD

**Issue by 8vius** [prawnpdf/prawn-table#112] opened 2019-02-21 21:10 UTC
I have some header elements set in the upper corners of my PDFs, a logo and some text, on the first page they look fine since I manually move down to start rendering the table:

<img width="1073" alt="screen shot 2019-02-21 at 3 03 28 pm" src="https://user-images.githubusercontent.com/671929/53201584-042a2100-35ea-11e9-8e90-e07e11347ed9.png">

But on every other page the top of the table is clipping with these elements:

<img width="1070" alt="screen shot 2019-02-21 at 3 03 24 pm" src="https://user-images.githubusercontent.com/671929/53201606-11471000-35ea-11e9-804e-41fadb3da11c.png">

This is how I'm rendering the logo and header text:

```
pdf.repeat :all do
  pdf.image(
    open(logo.url),
    fit: [160, 40],
    at: [pdf.bounds.right - (logo.metadata['width'] + 10), pdf.bounds.top + 10],
  )
end

pdf.draw_text(
  header_text,
  at: pdf.bounds.top_left,
  size: 8
)
```

And this is how I'm rendering out the table:

```
pdf.table(
  data,
  header: true,
  cell_style: { overflow: :shrink_to_fit, size: 6 },
  column_widths: column_widths
)
```

**Comment by gettalong** [comment] 2019-02-21 22:06
You could try setting the top margin so that it excludes your header area.

**Comment by pointlessone** [comment] 2019-02-22 13:29
This is expected behaviour even if it might seem surprising.

Prawn doesn't really have any layout tools. It' very close to the PDF drawing model. Objects do not push other objects (like they do in HTML, for example). They rather get put wherever the current position is happen to be. Many operation advance current position in a somewhat expected manner but that's about the extent of what is provided by Prawn.

This is even more evident with repeaters. Repeaters are getting applied *after* everything else. Think of them as being a completely separate pass through all the pages. After your document is finished, Prawn goes through each page and paints over whatever is in the repeaters. So if you want to avoid overlap you have to make sure there's enough blank space for them. One way, as Thomas suggested, would be to add margins. Alternatively, you can specify ac block that would be called right after creating a page with `on_page_create` method or `on_page_create_callback` option to document constructor.

---

I'll close this issue now as it's not a bug. Feel free to reopen if you believe it wasn't resolved.

**Closed by pointlessone** 2019-02-22 13:29 UTC
